# Generated by Django 3.2.12 on 2022-04-30 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('iban', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(choices=[('KZT', 'Kazakhstani Tenge'), ('RUR', 'Russian Rubles'), ('USD', 'US Dollars'), ('GBP', 'Great Britain Pounds'), ('EUR', 'Euro')], default='KZT', max_length=3)),
                ('balance', models.PositiveBigIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', related_query_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
