# Generated by Django 3.2.12 on 2022-05-01 18:46

import core.models.card
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitcard',
            name='card_number',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, validators=[core.models.card._card_number_validator]),
        ),
    ]
