# Generated by Django 3.2.12 on 2022-05-03 14:23

import core.models.deposit
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220501_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='due_date',
            field=models.DateField(default=core.models.deposit._get_default_deposit_due_date),
        ),
    ]
