# Generated by Django 3.2.12 on 2022-05-04 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_deposit_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='balance',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
